# ```yml
name: Generate Snake - GitHub Contribute Data

on:
  # auto run from Actions Tab
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
  schedule:
  - cron: "0 12 1 * *"
  # i.e. At 12:00 on day-of-month 1
  # e.g. at 2022-04-01 12:00:00

jobs:
  Snake:
    name: Generate Snake 🐍
    runs-on: ubuntu-latest
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./assets/github-contribution-grid-snake.gif
            ./assets/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}